// Code generated by "stringer -type=GameType"; DO NOT EDIT.

package model

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[GamePickFourEvening-29]
	_ = x[GamePickThreeEvening-28]
}

const _GameType_name = "GamePickThreeEveningGamePickFourEvening"

var _GameType_index = [...]uint8{0, 20, 39}

func (i GameType) String() string {
	idx := int(i) - 28
	if i < 28 || idx >= len(_GameType_index)-1 {
		return "GameType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _GameType_name[_GameType_index[idx]:_GameType_index[idx+1]]
}
